event/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.main, name='main'),
    path('ewa/', views.ewa, name='ewa'),
    path('conference/', views.conference, name='conf'),
    path('ewa/register/<str:random_id>/',
         views.ewa_delegate, name='ewa_delegate'),
    path('conference/register/<str:random_id>/',
         views.conference_delegate, name='conference_delegate'),
    path('profile/',
         views.past_events, name='past_events'),
]

events_platform/urls.py
import graphene
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from graphene_django.views import GraphQLView
from django.views.decorators.csrf import csrf_exempt
# from event.schema import schema

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('event.urls')),
    # path("graphql", csrf_exempt(GraphQLView.as_view(graphiql=False, schema=schema))),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

event/models.py
from django.db import models
from django.forms import DateField, FileField, IntegerField
from django.contrib.auth.models import User
from django.utils import timezone
from .choices import *
import uuid
from django.dispatch import receiver
from django.db.models.signals import post_save
# Create your models here.


class ConferenceType(models.Model):
    type = models.CharField(max_length=50)

    def __str__(self):
        return self.type


class AIESECer(models.Model):
    AIESECer = models.BooleanField()

    def __str__(self):
        return self.AIESECer


class LocalCommittee(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name

# abstract class for events


class Event(models.Model):
    lc_name = models.CharField(max_length=50, choices=LC)
    lc_representative = models.CharField(max_length=50)
    email = models.EmailField(null=True)
    event_name = models.CharField(max_length=50, unique=True)
    date = models.DateField(
        help_text="Please use the following format: YYYY-MM-DD")
    price = models.IntegerField()
    delegates_number = models.IntegerField()
    status = models.BooleanField(default=False)
    email_sent = models.BooleanField(default=False)
    registration_link = models.CharField(max_length=200, null=True, blank=True)
    random_id = models.CharField(
        max_length=200, default=uuid.uuid4(), unique=True)
    deadline = models.DateTimeField(
        default=timezone.now, null=True, blank=True)

    class Meta:
        abstract = True


class EwaEvent(Event):
    def __str__(self):
        return self.event_name + '_' + self.lc_name


class Conference(Event):
    conference_type = models.ForeignKey(
        ConferenceType, on_delete=models.CASCADE)

    def __str__(self):
        return self.event_name + '_' + self.lc_name


# delegates
class Delegate(models.Model):
    name = models.CharField(max_length=50)
    gender = models.CharField(max_length=50, choices=GENDER)
    phone_number = models.CharField(max_length=50)
    email = models.EmailField()
    cv = models.FileField(null=True, blank=True)
    indemnity_form = models.FileField(null=True)
    id_front = models.ImageField(null=True)
    id_back = models.ImageField(null=True)
    time_stamp = models.DateTimeField(default=timezone.now)

    class Meta:
        abstract = True


class EwaDelegate(Delegate):
    event = models.ForeignKey(EwaEvent, on_delete=models.CASCADE, null=True)
    aiesecer = models.ForeignKey(AIESECer, on_delete=models.CASCADE)
    lc = models.ForeignKey(LocalCommittee, on_delete=models.CASCADE)
    role = models.CharField(max_length=50, null=True,
                            blank=True, choices=NATIONAL_ROLE)
    function = models.CharField(
        max_length=50, null=True, blank=True, choices=NATIONAL_FUNCTION)

    def __str__(self):
        return self.name


class NationalConferenceDelegate(Delegate):
    event = models.ForeignKey(Conference, on_delete=models.CASCADE, null=True)
    lc = models.CharField(max_length=50, null=True,
                          blank=True, choices=LC, verbose_name='LC')
    role = models.CharField(max_length=50, null=True,
                            blank=True, choices=NATIONAL_ROLE)
    function = models.CharField(
        max_length=50, null=True, blank=True, choices=NATIONAL_FUNCTION)

    def __str__(self):
        return self.name


class LocalConferenceDelegate(Delegate):
    event = models.ForeignKey(Conference, on_delete=models.CASCADE, null=True)
    lc = models.CharField(max_length=50, null=True,
                          blank=True, choices=LC, verbose_name='LC')
    role = models.CharField(max_length=50, null=True,
                            blank=True, choices=LOCAL_ROLE)
    function = models.CharField(
        max_length=50, null=True, blank=True, choices=LOCAL_FUNCTION)

    def __str__(self):
        return self.name


# User

class Entity(models.Model):
    name = models.CharField(max_length=100)
    parent = models.ForeignKey(
        'self', null=True, blank=True, on_delete=models.CASCADE)
    expa_id = models.IntegerField()

    def __str__(self):
        return self.name


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    expa_id = models.IntegerField(null=True, blank=True)
    first_name = models.CharField(max_length=250)
    last_name = models.CharField(max_length=250)
    full_name = models.CharField(max_length=250)
    gender = models.CharField(max_length=100, null=True, blank=True)
    status = models.CharField(max_length=100)
    home_lc = models.CharField(max_length=250, null=True, blank=True)
    email = models.CharField(max_length=250, null=True, blank=True)
    phone = models.CharField(max_length=250, null=True, blank=True)
    facebook = models.CharField(max_length=500, null=True, blank=True)
    instagram = models.CharField(max_length=500, null=True, blank=True)
    applications_count = models.IntegerField(default=0)
    joined_at = models.DateField(null=True, blank=True)
    access = models.CharField(max_length=400, null=True, blank=True)
    is_icx = models.BooleanField(default=False)
    is_ogx = models.BooleanField(default=False)
    role = models.CharField(max_length=250, null=True, blank=True)

    def __str__(self):
        return self.full_name

templates/forms/conference.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <form method="post" novalidate>
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Submit">
    </form>
</body>
</html>

templates/forms/delegate.html
{% load static %}
{% load widget_tweaks %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'assets/css/form.css' %}">
    <title>Document</title>
</head>
<body>
    <section class="form-container">
        <form enctype="multipart/form-data" method="post" novalidate>
            {% csrf_token %}
            <div class="form">
                <p class="form-item form-item1">
                    <label for="id_name">Name:</label>
                    {% render_field form.name %}
                </p>
                <p class="form-item form-item1">
                    <label for="id_gender">Gender:</label>
                    {% render_field form.gender %}
                </p>
                <p class="form-item form-item2">
                    <label for="id_phone_number">Phone number:</label>
                    {% render_field form.phone_number %}
                </p>
                <p class="form-item form-item2">
                    <label for="id_email">Email:</label>
                    {% render_field form.email %}
                </p>
                <p class="form-item form-item3">
                    <label for="id_cv">Cv:</label>
                    {% render_field form.cv %}
                </p>
                <p class="form-item form-item3">
                    <label for="id_indemnity_form">Indemnity form:</label>
                    {% render_field form.indemnity_form %}
                </p>
                <p class="form-item form-item4">
                    <label for="id_id_front">Id front:</label>
                    {% render_field form.id_front %}
                </p>
                <p class="form-item form-item4">
                    <label for="id_id_back">Id back:</label>
                    {% render_field form.id_back %}
                </p>
                <p class="form-item form-item5">
                    <label for="id_lc">LC:</label>
                    {% render_field form.lc %}
                </p>
                <p class="form-item form-item5">
                    <label for="id_role">Role:</label>
                    {% render_field form.role %}
                </p>
                <p class="form-item form-item6">
                    <label for="id_function">Function:</label>
                    {% render_field form.function %}
                </p>
                <div class="btn-container">
                    <input id="submit" class="btn btn-glow form-btn" type="submit" name="submit" value="Submit"/>
                </div>
            </div>
        </form>
    </section>
</body>
</html>

templates/forms/ewa.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <form method="post" novalidate>
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Submit">
    </form>
</body>
</html>